--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/supercrafter333/BlockAPI
build-by-default: true
branches:
  - master
  - PMMP_API_4
projects:
  BlockAPI:
    icon: "icon.png"
    path: ""
...
