name: BlockAPI
version: 1.1.0-API4-dev
api: 4.0.0
main: supercrafter333\BlockAPI\BlockAPILoader
author: supercrafter333

permissions:
  blockapi.block.cmd:
    description: Command permission
    default: op
  blockapi.unblock.cmd:
    description: Command permission
    default: op
  blockapi.checkblockstatus.cmd:
    description: Command permission
    default: op